name: Gaming Builder Tests
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: Run Automated Tests
    runs-on: ubuntu-latest
    steps:
      - name: "Check Out Branch"
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.0.0"
          cache: "yarn"

      - name: Install NPM Dependensies
        run: yarn install

      - name: Build Application
        run: vite build
